export const PRICING_TIERS = [
    {
        id: 'weekly',
        name: 'Weekly Access',
        priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_WEEKLY || 'price_weekly_placeholder',
        price: '$29',
        interval: 'week',
        description: 'Perfect for short-term project needs',
        features: [
            'Full Database Access',
            'Unlimited Deal Analysis',
            'Vendor Directory Access',
            'Community Forum Access',
        ],
        highlight: false,
        badge: 'Flexibility',
        valueHook: 'Full Flexibility',
    },
    {
        id: 'monthly',
        name: 'Monthly Access',
        priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_MONTHLY || 'price_monthly_placeholder',
        price: '$99',
        interval: 'month',
        description: 'Our most popular plan for active investors',
        features: [
            'Everything in Weekly',
            'Priority Support',
            'Advanced Market Analytics',
            'Deal Alerts',
        ],
        highlight: true,
        badge: 'Most Popular',
        valueHook: 'Most Popular',
    },
    {
        id: 'biannual',
        name: 'Bi-Annual Access',
        priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_BIANNUAL || 'price_biannual_placeholder',
        price: '$495',
        interval: '6 months',
        description: 'Commit to your growth and save',
        features: [
            'Everything in Monthly',
            '1 Month Free',
            'Quarterly Strategy Calls',
        ],
        highlight: false,
        badge: 'Best Value',
        valueHook: '1 Month Free',
        savings: '$99',
    },
    {
        id: 'annual',
        name: 'Annual Access',
        priceId: process.env.NEXT_PUBLIC_STRIPE_PRICE_ID_ANNUAL || 'price_annual_placeholder',
        price: '$990',
        interval: 'year',
        description: 'Maximum savings for serious investors',
        features: [
            'Everything in Bi-Annual',
            '2 Months Free',
            'VIP Event Access',
        ],
        highlight: false,
        badge: 'Max Savings',
        valueHook: '2 Months Free',
        savings: '$198',
    },
];
