import { VendorListing } from "./types";

export const exampleVendors: VendorListing[] = [
    {
        id: "sample-1",
        name: "Lone Star General Builders",
        tagline: "Investor-first general contracting crew across North + Central Texas",
        description:
            "Design-build GC that understands holding costs and lender draw schedules. We manage scopes, subs, and permitting so investors keep velocity high.",
        location: "Dallas, TX",
        marketAreas: ["Dallas-Fort Worth", "Austin", "Waco/Temple"],
        workTypes: ["General Contracting", "Framing & Carpentry", "Project Management"],
        verificationStatus: "verified",
        contact: {
            name: "Maria Ortiz",
            phone: "(214) 555-0134",
            email: "maria@lonestargb.com",
            website: "https://lonestargb.com",
        },
        logoUrl: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=200&q=80",
        avatarUrl: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=400&q=80",
        bannerUrl: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1200&q=80",
        pastProjects: [
            {
                title: "7-unit SFR portfolio refresh",
                location: "Fort Worth, TX",
                budget: "$185k",
                referenceName: "J. Simmons, REI",
                referenceContact: "214-555-2290",
                description: "Fast-track exterior facelifts and make-ready turns for scattered-site rentals.",
            },
            {
                title: "Historic duplex conversion",
                location: "Old East Dallas",
                budget: "$240k",
                referenceName: "Kim Tran, investor",
                description: "Managed permits, structural framing, and finish coordination to hit ARV appraisal.",
            },
        ],
    },
    {
        id: "sample-2",
        name: "Bluebonnet Plumbing & Mechanical",
        tagline: "Licensed plumbing + gas with 24/7 investor service line",
        description:
            "Rough-ins, repipes, water heaters, and gas tests with photo documentation for lenders and inspectors.",
        location: "Houston, TX",
        marketAreas: ["Houston", "Dallas-Fort Worth"],
        workTypes: ["Plumbing", "Gas Lines", "Sewer & Water"],
        verificationStatus: "verified",
        contact: {
            name: "Andre Delgado",
            phone: "(832) 555-0147",
            email: "andre@bluebonnetplumbing.com",
            website: "https://bluebonnetplumbing.com",
        },
        logoUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=200&q=80",
        avatarUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=400&q=80",
        bannerUrl: "https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?auto=format&fit=crop&w=1200&q=80",
        pastProjects: [
            {
                title: "Multifamily boiler replacement",
                location: "Spring Branch, TX",
                budget: "$96k",
                referenceName: "C. Patel, operator",
                description: "Replaced boilers and circulating pumps with zero downtime for tenants.",
            },
            {
                title: "Whole-home PEX repipe",
                location: "Plano, TX",
                budget: "$18k",
                referenceName: "A. Nguyen",
                description: "3-day turnaround with drywall patches included for make-ready schedule.",
            },
        ],
    },
    {
        id: "sample-3",
        name: "Skyline Roofing & Exteriors",
        tagline: "Insurance-savvy roofers who protect ARV and closing timelines",
        description:
            "Full roof replacements, gutters, and exterior repairs with investor-friendly bids and drone documentation.",
        location: "San Antonio, TX",
        marketAreas: ["San Antonio", "Dallas-Fort Worth", "Coastal Texas"],
        workTypes: ["Roofing", "Gutters", "Exterior Trim"],
        verificationStatus: "verified",
        contact: {
            name: "Lena Fowler",
            phone: "(210) 555-0190",
            email: "lena@skylineexteriors.com",
            website: "https://skylineexteriors.com",
        },
        logoUrl: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=200&q=80",
        avatarUrl: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=400&q=80",
        bannerUrl: "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?auto=format&fit=crop&w=1200&q=80",
        pastProjects: [
            {
                title: "Hail claim replacement",
                location: "Frisco, TX",
                budget: "$32k",
                referenceName: "E. Carter, investor",
                description: "Handled adjuster meetings and photo sets to keep closing on track.",
            },
            {
                title: "Metal roof + gutter upgrade",
                location: "Rockport, TX",
                budget: "$54k",
                referenceName: "Bayfront Capital",
                description: "Coastal wind specs, stainless fasteners, and gutter guards for rentals.",
            },
        ],
    },
    {
        id: "sample-4",
        name: "Hill Country HVAC & Electrical",
        tagline: "Comfort systems tuned for rental durability",
        description:
            "Installations, change-outs, and electrical upgrades with load calcs, permits, and warranty tracking.",
        location: "Austin, TX",
        marketAreas: ["Austin", "Texas Hill Country", "San Antonio"],
        workTypes: ["HVAC", "Electrical", "Smart Home"],
        verificationStatus: "verified",
        contact: {
            name: "Chris Salinas",
            phone: "(737) 555-0172",
            email: "service@hchvac.com",
            website: "https://hillcountryhvac.com",
        },
        logoUrl: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=200&q=80",
        avatarUrl: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=400&q=80",
        bannerUrl: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1200&q=80",
        pastProjects: [
            {
                title: "Mini-split package for STR",
                location: "Fredericksburg, TX",
                budget: "$28k",
                referenceName: "L. Edwards",
                description: "Zone control install with smart thermostats and remote monitoring.",
            },
            {
                title: "Panel and service upgrade",
                location: "Round Rock, TX",
                budget: "$12k",
                referenceName: "North Loop Rentals",
                description: "200A upgrade with AFCI/GFCI compliance for lender inspection.",
            },
        ],
    },
    {
        id: "sample-5",
        name: "Coastal Finish Drywall + Paint",
        tagline: "Clean finishes, investor-grade pricing",
        description:
            "Drywall hangs, level 4/5 finishes, texture matching, and interior/exterior paint crews ready for quick turns.",
        location: "League City, TX",
        marketAreas: ["Houston", "Coastal Texas"],
        workTypes: ["Drywall & Paint", "Texture & Repair", "Cabinet Refinishing"],
        verificationStatus: "verified",
        contact: {
            name: "Tamika Johnson",
            phone: "(409) 555-0114",
            email: "projects@coastalfinish.com",
        },
        logoUrl: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=200&q=80",
        avatarUrl: "https://images.unsplash.com/photo-1562259949-e8e7689d7828?auto=format&fit=crop&w=400&q=80",
        bannerUrl: "https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=1200&q=80",
        pastProjects: [
            {
                title: "Full interior repaint + cabinets",
                location: "Clear Lake, TX",
                budget: "$14k",
                referenceName: "Harbor Homes",
                description: "Sprayed cabinets, trim enamel, and LVP-friendly base replacement.",
            },
            {
                title: "Sheetrock + texture match",
                location: "Pasadena, TX",
                budget: "$8k",
                referenceName: "S. Rios",
                description: "Insurance patch work blended to existing orange peel and knockdown.",
            },
        ],
    },
    {
        id: "sample-6",
        name: "GreenBelt Landscape & Outdoor",
        tagline: "Curb appeal and outdoor living that sell the deal",
        description:
            "From sod and irrigation fixes to full hardscape installs. We build durable, low-maintenance exteriors for rentals and flips.",
        location: "Austin, TX",
        marketAreas: ["Austin", "Texas Hill Country", "San Antonio"],
        workTypes: ["Landscaping", "Hardscapes", "Fencing"],
        verificationStatus: "verified",
        contact: {
            name: "Robin Keller",
            phone: "(512) 555-0188",
            email: "robin@greenbeltoutdoor.com",
            website: "https://greenbeltoutdoor.com",
        },
        logoUrl: "https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=200&q=80",
        avatarUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=400&q=80",
        bannerUrl: "https://images.unsplash.com/photo-1558904541-efa843a96f01?auto=format&fit=crop&w=1200&q=80",
        pastProjects: [
            {
                title: "Rental-friendly landscape refresh",
                location: "Pflugerville, TX",
                budget: "$9k",
                referenceName: "Vista REI",
                description: "Drought-tolerant plant palette, drip irrigation, and decomposed granite paths.",
            },
            {
                title: "Outdoor living + privacy package",
                location: "New Braunfels, TX",
                budget: "$22k",
                referenceName: "Ryan Properties",
                description: "Cedar fence, pergola, and lighting to boost appraisal photos.",
            },
        ],
    },
];
